{"name": "test_rerun_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "self = <tests.pytest.test_reruns.TestReruns object at 0x10cd690a0>\n\n    def test_rerun_2(self):\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests/pytest/test_reruns.py:19: AssertionError"}, "start": 1751216058425, "stop": 1751216058425, "uuid": "c58f67b5-6bed-461b-aea8-04df4aaeccc6", "historyId": "df1662c89c40c287908e0e99c9c0d00f", "testCaseId": "df1662c89c40c287908e0e99c9c0d00f", "fullName": "tests.pytest.test_reruns.TestReruns#test_rerun_2", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "subSuite", "value": "TestReruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "79947-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}