{"name": "test_without_bug", "status": "passed", "statusDetails": {"message": "XPASS Баг уже исправлен, но на тест все еще висит маркировка xfail"}, "start": 1751219706392, "stop": 1751219706392, "uuid": "6855e61a-b4ea-4c8c-a003-cf76463d6e25", "historyId": "bb33ef2621d46ef1f1d5cda365e5afa3", "testCaseId": "bb33ef2621d46ef1f1d5cda365e5afa3", "fullName": "tests.pytest.test_pytest_xfail#test_without_bug", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_pytest_xfail"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "88573-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_pytest_xfail"}]}