{"name": "test_rerun_with_condition", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = choice([True, False])\n +    where choice = random.choice", "trace": "@pytest.mark.flaky(reruns=3, reruns_delay=2, condition=PLATFORM == \"Windows\")  # Перезапуск при выполнении условия\n    def test_rerun_with_condition():\n>       assert random.choice([True, False])\nE       assert False\nE        +  where False = choice([True, False])\nE        +    where choice = random.choice\n\ntests/pytest/test_reruns.py:24: AssertionError"}, "start": 1751216060447, "stop": 1751216060447, "uuid": "537c8f33-a268-4170-92b4-f7f4c66e0a0c", "historyId": "431c2bc8b3d1acdf6a5f6ac2f94650a9", "testCaseId": "431c2bc8b3d1acdf6a5f6ac2f94650a9", "fullName": "tests.pytest.test_reruns#test_rerun_with_condition", "labels": [{"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_reruns"}, {"name": "host", "value": "MacBook-Pro-Tochka-2.local"}, {"name": "thread", "value": "79947-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_reruns"}]}